//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;id_4fcd4dd6-050f-419b-9578-4f7081e6d775&quot;,
        ///  &quot;rcId&quot;: 101,
        ///  &quot;name&quot;: &quot;IDD_FORMVIEW&quot;,
        ///  &quot;type&quot;: 66,
        ///  &quot;style&quot;: 8,
        ///  &quot;x&quot;: 0,
        ///  &quot;y&quot;: 0,
        ///  &quot;width&quot;: 185,
        ///  &quot;height&quot;: 93,
        ///  &quot;child&quot;: true,
        ///  &quot;fontSize&quot;: 8,
        ///  &quot;fontName&quot;: &quot;MS Shell Dlg&quot;,
        ///  &quot;items&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;id_e7a0ca5d-5f2b-4ce9-a4da-88d9da87d8f5&quot;,
        ///      &quot;rcId&quot;: 8369,
        ///      &quot;name&quot;: &quot;IDC_EDIT1&quot;,
        ///      &quot;type&quot;: 13,
        ///      &quot;x&quot;: 7,
        ///      &quot;y&quot;: 26,
        ///      &quot;width&quot;: 40,
        ///      &quot;height&quot;: 14,
        ///      &quot;autoHScroll&quot;: true
        ///    },
        ///    {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDD_FORMVIEW {
            get {
                return ResourceManager.GetString("IDD_FORMVIEW", resourceCulture);
            }
        }
    }
}
